name: Test
on:
  push:
jobs:
  LintCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test:cov
